"""
Django settings for hris project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4&quhz))qhg9a(t#^fmycf=bf=dn#5n$k1k2d61)u+d&=ro8e#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CORS_ALLOW_ALL_ORIGINS = True
USE_TZ = False

# CORS settings. CORS_ALLOW_ALL_ORIGINS above already lets any origin call the
# API; these are listed so the deployed origins stay allowed if that is ever
# turned off, and so the same list can be reused for CSRF below.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite (React dev server)
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://192.168.157.55:2025",  # the portal, served by Apache
    "http://192.168.157.55:9000",
]

# Needed for form posts and the Django admin when they come from another origin.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

# Host names only - an entry with a port never matches, which is why the old
# "192.168.157.55:9000" line did nothing.
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "192.168.157.55",
    "172.16.17.50",
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',  # If you're using Django Extensions
    'corsheaders',  # If you're using Django Extensions
    'attendance',  # Your attendance app
    'users',  # Your attendance app
    'sections',  # Your attendance app
    'leaves',  # Your attendance app
    'holidays',  # Your attendance app
    'mainmenu',  # Your main menu app
    'submenu',  # Your submenu app
    'assignrights',
    'jobs',
    'addtouser',
    'officialwork',
    'notifications',  # In-app notifications shown in the top navbar
    'rest_framework',  # If you're using Django REST Framework
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hris.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hris.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'Attendance_System',  # Replace with your actual database name
        'USER': 'sa',
        'PASSWORD': 'Sa@157',
        'HOST': '192.168.157.51',
        'PORT': '9090',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # Ensure you have the correct ODBC driver installed
            'charset': 'utf8mb4',  # Optional, adjust as needed
            'extra_params': 'TrustServerCertificate'  # Optional, adjust as needed
        },

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uploaded files (currently: medical records attached to leave applications).
# Served through leaves.views.download_leave_attachment rather than as plain
# static files, so the stored name never has to be guessable.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Attachment limits, applied in leaves.views.create_leave_request.
LEAVE_ATTACHMENT_MAX_MB = 5
LEAVE_ATTACHMENT_ALLOWED_EXTENSIONS = [
    '.pdf', '.jpg', '.jpeg', '.png', '.webp', '.heic', '.doc', '.docx',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
