# Generated by Django 5.0.14 on 2026-06-04 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businessplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.IntegerField()),
                ('task_description', models.TextField()),
                ('risk_comment', models.TextField(blank=True, default='')),
                ('activity_date', models.DateField()),
                ('today_progress', models.IntegerField(default=0)),
                ('overall_pct', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='In Progress', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bp_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='businessplan.businessplan')),
            ],
            options={
                'db_table': 'employee_activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
