# Generated by Django 5.0.14 on 2025-07-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authid', models.IntegerField()),
                ('erpid', models.IntegerField()),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
