# Generated by Django 5.0.14 on 2026-06-01 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_number', models.CharField(max_length=30, unique=True)),
                ('parent_sr', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=500)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('lead_team', models.CharField(blank=True, max_length=100)),
                ('support_team', models.CharField(blank=True, max_length=100)),
                ('dependencies', models.CharField(blank=True, max_length=200)),
                ('deliverables', models.CharField(blank=True, max_length=200)),
                ('completion_pct', models.IntegerField(default=0)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_by_grade', models.IntegerField()),
            ],
            options={
                'db_table': 'business_plan',
                'ordering': ['sr_number'],
            },
        ),
    ]
