# Generated by Django 4.2.30 on 2026-06-15 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('businessplan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessplan',
            name='department',
        ),
        migrations.AddField(
            model_name='businessplan',
            name='section',
            field=models.ForeignKey(blank=True, db_column='section_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.sections'),
        ),
    ]
