# Generated by Django 4.2.30 on 2026-06-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('businessplan', '0002_remove_businessplan_department_businessplan_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='section',
            field=models.ForeignKey(blank=True, db_column='section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.sections'),
        ),
    ]
