# Generated by Django 5.2.3 on 2025-07-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'public_holidays',
            },
        ),
    ]
