# Generated by Django 4.2.30 on 2026-06-16 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_section_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('head_employee', models.ForeignKey(db_column='head_employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='headed_sub_sections', to='users.employees')),
                ('section', models.ForeignKey(db_column='section_id', on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='sections.sections')),
            ],
            options={
                'db_table': 'sub_sections',
                'ordering': ['-created_at'],
            },
        ),
    ]
