# Generated by Django 5.0.14 on 2025-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=250)),
                ('punch', models.IntegerField(blank=True, null=True)),
                ('lateintime', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
