# Generated by Django 5.0.14 on 2026-01-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavemodel_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeCountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, max_length=50, null=True)),
                ('total_leaves', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'leave_type_counts',
            },
        ),
    ]
