# Generated by Django 5.0.14 on 2026-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_leavetypecountmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
    ]
