# Generated by Django 5.0.14 on 2026-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_leavemodel_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='entry_made_by',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
