# Generated by Django 5.0.14 on 2026-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_leavemodel_entry_made_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='entry_made_by',
            field=models.IntegerField(default=0),
        ),
    ]
