# Generated by Django 5.0.14 on 2026-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0008_leavemodel_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='is_lwp_overflow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavemodel',
            name='lwp_days',
            field=models.IntegerField(default=0),
        ),
    ]
