# Generated by Django 5.0.14 on 2026-09-18 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0009_leavemodel_is_lwp_overflow_leavemodel_lwp_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApprovalStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('label', models.CharField(max_length=100)),
                ('role_key', models.CharField(max_length=32)),
                ('assigned_erp_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('acted_by_erp_id', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_stages', to='leaves.leavemodel')),
            ],
            options={
                'db_table': 'leave_approval_stages',
                'ordering': ['leave_id', 'sequence'],
                'unique_together': {('leave', 'sequence')},
            },
        ),
    ]
