# Generated by Django 5.0.14 on 2026-08-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_erp_id', models.IntegerField(db_index=True)),
                ('emp_full_name', models.CharField(max_length=150)),
                ('emp_id', models.IntegerField()),
                ('current_dept_code', models.CharField(max_length=200)),
                ('current_job_title', models.CharField(max_length=200)),
                ('current_supervisor_id', models.CharField(max_length=150)),
                ('current_supervisor_erp_id', models.IntegerField(blank=True, null=True)),
                ('cnic', models.CharField(max_length=15)),
                ('contact_phone_no', models.CharField(max_length=25)),
                ('corporate_email', models.EmailField(max_length=150)),
                ('personal_email', models.EmailField(blank=True, max_length=150, null=True)),
                ('preferred_contact_method', models.CharField(max_length=10)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'internal_job_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'job_requisitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternalJobApplicationEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_degree_title', models.CharField(max_length=200)),
                ('edu_institution_name', models.CharField(max_length=200)),
                ('edu_major_specialization', models.CharField(max_length=200)),
                ('edu_graduation_year', models.IntegerField()),
                ('edu_grade_score', models.CharField(max_length=40)),
                ('row_order', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='jobs.internaljobapplication')),
            ],
            options={
                'db_table': 'internal_job_application_education',
                'ordering': ['row_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='internaljobapplication',
            name='target_job_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.jobrequisition'),
        ),
    ]
