# Generated by Django 5.0.14 on 2026-08-24 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internaljobapplication',
            name='ack_data_accuracy_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaljobapplication',
            name='ack_manager_notified_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internaljobapplication',
            name='application_rationale_sop',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='internaljobapplication',
            name='certifications_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InternalJobApplicationExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_job_title', models.CharField(max_length=200)),
                ('exp_company_name', models.CharField(max_length=200)),
                ('exp_start_date', models.DateField()),
                ('exp_end_date', models.DateField(blank=True, null=True)),
                ('exp_is_current', models.BooleanField(default=False)),
                ('exp_key_responsibilities', models.TextField()),
                ('exp_key_achievements', models.TextField(blank=True, null=True)),
                ('row_order', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='jobs.internaljobapplication')),
            ],
            options={
                'db_table': 'internal_job_application_experience',
                'ordering': ['row_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InternalJobApplicationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(db_index=True, max_length=10)),
                ('skill_name', models.CharField(max_length=80)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.internaljobapplication')),
            ],
            options={
                'db_table': 'internal_job_application_skills',
                'ordering': ['skill_type', 'id'],
            },
        ),
    ]
