# Generated by Django 5.0.14 on 2026-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_official_form_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaljobapplication',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='internaljobapplication',
            name='mobile_no',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='internaljobapplication',
            name='official_email',
            field=models.EmailField(max_length=150),
        ),
    ]
