# Generated by Django 5.0.14 on 2026-09-07 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_align_form_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=40, null=True)),
                ('reports_to', models.CharField(blank=True, max_length=200, null=True)),
                ('job_purpose', models.TextField(blank=True, null=True)),
                ('key_responsibilities', models.TextField()),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience_required', models.TextField(blank=True, null=True)),
                ('skills_competencies', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_descriptions',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='jobrequisition',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='jobs.jobdescription'),
        ),
    ]
