# Generated by Django 5.2.3 on 2025-06-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('privilege', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=150)),
                ('group_id', models.CharField(blank=True, max_length=250, null=True)),
                ('card', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
