# Generated by Django 5.0.14 on 2025-07-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.IntegerField()),
                ('hris_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=1)),
                ('section_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('grade_id', models.IntegerField()),
                ('designation_id', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('privilege', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('card', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
