# Generated by Django 5.0.14 on 2026-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
